/* generated by tools/gen_boot_anim.js - do not edit */
#pragma once

#include <stdint.h>

/* Pen path in screen space, 1/16 px units. Polylines are slices of
 * boot_path_points[]: polyline i spans [poly_start[i], poly_start[i+1]). */
typedef struct {
    int16_t x;
    int16_t y;
} boot_path_pt_t;

extern const boot_path_pt_t boot_path_points[];
extern const uint16_t boot_path_poly_start[];
extern const uint16_t boot_path_poly_count;
extern const uint32_t boot_path_total_q;
